using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;

namespace MasterMindConsoleApp
{
    internal class Program
    {
        static void Main(string[] args)
        {

            int NumberOfAttempt = 0;

            //Generate 4 digit random number 
            int Min = 1;
            int Max = 6;
            Random r = new Random();
            String S1 = r.Next(Min, Max).ToString();
            String S2 = r.Next(Min, Max).ToString();
            String S3 = r.Next(Min, Max).ToString();
            String S4 = r.Next(Min, Max).ToString();
            string randomNumber = (S1 + S2 + S3 + S4);
            int randomNumer = int.Parse(randomNumber);
            Console.WriteLine("Enter the Random Numer :" + randomNumer);
            Console.WriteLine("Pllease enter the four (4) digits number, with each digit between the numbers 1 and 6");

            
            do
            
            {
                string Input = Console.ReadLine();
                int inputVal = 0;
                NumberOfAttempt++;

                //validate the input for valid digits
                if (Input.All(char.IsNumber)== true && Input.Length == 4 && Input.All(c => c >= '1' && c <= '6'))
                {

                    inputVal = Convert.ToInt32(Input);
                   

                    //Terminating loop if number of inputs reached max value
                    if (NumberOfAttempt == 10)
                    {
                        Console.WriteLine("Number of attempts reached MAX");

                        
                    }
                    //verify the input against random number generated by system
                    else
                    {
                       //compare entire input with random number and terminate if its matches
                        string OutputVal = "";
                        if (randomNumer == inputVal)
                        {
                            OutputVal = "  ++++";
                            Console.WriteLine("   :" + OutputVal);
                            Console.WriteLine(" Correct answer");
                            NumberOfAttempt = 10;
                        }
                        //compare each digit of input with random number
                        else
                        {
                            
                            int InputLength = Input.Length;
                            int RandomLength = randomNumer.ToString().Length;
                            for (int i = 0; i <= InputLength - 1; i++)
                            {
                                //Check the value and position matches
                                if (Input[i] == randomNumber[i])
                                    OutputVal += "+";
                                //check the value present but in different position
                                else if (randomNumber.Contains(Input[i]) && Input[i] != randomNumber[i])
                                    OutputVal += "-";
                            }
                           // displays the compare output in the sequense plus minus and blank
                            Console.WriteLine("   :"+ String.Concat(OutputVal.OrderBy(c => c)));

                        }

                    }
                }
                else
                {
                    //validation error for input
                   if(NumberOfAttempt<=10 || Input.Length == 4)
                     Console.WriteLine("Enter the valid 4 digit number between 1 to 6 digit");
                   

                }
               
           } while (NumberOfAttempt <=10) ;

           
               
            
        }
    }
}
